config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :delete, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="form-container">
  <h1>Edit Flat</h1>
  <%= simple_form_for flat_path(@flat) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :img %>
      <%= f.input :description %>
      <%= f.input :number_of_guests %>
      <%= f.input :price_per_night %>
      <div class="d-flex">
        <%= f.submit class: 'btn btn-success mt-3' %>
        <%= link_to 'Cancel', flat_path(@flat), class: 'btn btn-warning mt-3 ms-3'  %>
      </div>
  <% end %>
</div>

app/views/flats/index.html.erb
<h1>Flats</h1>
<div class="d-flex justify-content-around">
  <% @flats.each do |flat| %>
    <div class="card me-2" style="width: 18rem;">
      <img class="card-img-top" src= <%= flat.img %> alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"> <%= flat.name %> </h5>
        <p class="card-text"> <%= flat.description %> </p>
        <div class="d-flex justify-content-around border-bottom pb-2">
          <div class="d-flex">
            img
            <p class="card-text"> <strong> <%= flat.number_of_guests %> </strong> </p>
          </div>
          <div class="d-flex">
            img
            <p class="card-text"> <strong> <%= flat.price_per_night %> </strong> </p>
          </div>
        </div>
        <div class="d-flex justify-content-around mt-3">
          <%= link_to 'More info', flat_path(flat),  class: "btn btn-sm btn-primary"%>
          <%= link_to 'Edit', edit_flat_path(flat),  class: "btn btn-sm btn-success"%>
          <%= link_to 'Remove', flat_path(flat), method: :delete,  class: "btn btn-sm btn-warning"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>Flats#new</h1>
<p>Find me in app/views/flats/new.html.erb</p>

app/views/flats/show.html.erb
<div>BACKGROUND IMAGE</div>
<div class="show-container">
  <div class="d-flex">
    <div>
      <div class="card p-3 me-3 mb-2">
        <h1 class="card-title"> <%= @flat.name %> </h1>
        <p class="card-subtitle muted"> <%= @flat.address %> </p>
      </div>

      <div class="card p-3  me-3">
        <h3 class="card-title">A bit more about this flat </h1>
        <p class="card-subtitle"> <%= @flat.description %> </p>
      </div>
    </div>

    <div>
      <div class="card p-3 mb-2">
        <h4 class="card-title">Book this place!</h4>
        <form>
          <div class="form">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">From</span>
              </div>
              <input type="date" class="form-control" placeholder="from" aria-label="from" aria-describedby="basic-addon1">
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">To</span>
              </div>
              <input type="date" class="form-control" placeholder="to" aria-label="to" aria-describedby="basic-addon1">
            </div>
          </div>
        </form>
      </div>

      <div>
        <div class="card p-3 mb-2">
          <h3 class="card-title">Details</h3>
          <div class="d-flex">
            <div class="d-flex">
              img
              <p> <%= @flat.number_of_guests %> </p>
            </div>
            <div class="d-flex">
              img
              <p> <%= @flat.price_per_night %> </p>
            </div>
          </div>
        </div>
      </div>

      <div class="card p-3 mb-2">
        <div class="d-flex justify-content-between">
          <p class="card-title">Share</p>
          <div class="d-flex">
            <i>f</i>
            <i>b</i>
            <i>c</i>
            <i>s</i>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>